apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: RMQ_URL
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: RMQ_URL
             - name: FILES_TCP_HOST
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: FILES_TCP_HOST
             - name: FILES_STREAMING_PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: FILES_STREAMING_PORT
             - name: FILES_POSTGRES_URL
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: FILES_POSTGRES_URL
             - name: S3_ENDPOINT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: S3_ENDPOINT
             - name: S3_ACCESS_KEY_ID
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: S3_ACCESS_KEY_ID
             - name: S3_SECRET_ACCESS_KEY
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: S3_SECRET_ACCESS_KEY
             - name: S3_BUCKET
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: S3_BUCKET
             - name: S3_REGION
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: S3_REGION
             - name: FILES_TCP_PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-files-production-config-secret
                   key: FILES_TCP_PORT