apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: PAYMENTS_TCP_HOST
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: PAYMENTS_TCP_HOST
             - name: RMQ_URL
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: RMQ_URL
             - name: PAYMENTS_POSTGRES_URL
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: PAYMENTS_POSTGRES_URL
             - name: FRONTEND_PAYMENTS_REDIRECT_URL
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: FRONTEND_PAYMENTS_REDIRECT_URL
             - name: STRIPE_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: STRIPE_SECRET_KEY
             - name: STRIPE_API_VERSION
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: STRIPE_API_VERSION
             - name: STRIPE_WEBHOOK_SECRET
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: STRIPE_WEBHOOK_SECRET
             - name: PAYPAL_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: PAYPAL_CLIENT_ID
             - name: PAYPAL_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: PAYPAL_SECRET_KEY
             - name: PAYPAL_IS_SANDBOX
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: PAYPAL_IS_SANDBOX
             - name: PAYMENTS_TCP_PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-payments-production-config-secret
                   key: PAYMENTS_TCP_PORT