apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: AUTH_CLIENT_HOST
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: AUTH_CLIENT_HOST
             - name: AUTH_CLIENT_PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: AUTH_CLIENT_PORT
             - name: MAIN_CLIENT_HOST
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: MAIN_CLIENT_HOST
             - name: MAIN_CLIENT_PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: MAIN_CLIENT_PORT
             - name: NOTIFICATIONS_CLIENT_HOST
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: NOTIFICATIONS_CLIENT_HOST
             - name: NOTIFICATIONS_CLIENT_PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: NOTIFICATIONS_CLIENT_PORT
             - name: ACCESS_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: ACCESS_SECRET_KEY
             - name: ACCESS_EXPIRES_IN
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: ACCESS_EXPIRES_IN
             - name: ALLOWED_ORIGINS
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: ALLOWED_ORIGINS
             - name: PORT
               valueFrom:
                 secretKeyRef:
                   name: ulens-backend-gateway-production-config-secret
                   key: PORT